spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hungerfool?useUnicode=true&useSSL=false
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver
  mail: 
     host: smtp.mxhichina.com
     username: notification@hungerfool.com
     password: 1qaz@wsx
     properties:
       mail: 
         smtp: 
           auth: true
#           starttls: 
#             enable: true
#             required: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
http: 
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
  
